return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "autotools-language-server",
        "bash-language-server",
        "checkstyle",
        "codeql",
        "css-lsp",
        "gh",
        "groovy-language-server",
        "hadolint",
        "html-lsp",
        "htmlhint",
        "java-debug-adapter",
        "java-language-server",
        "java-test",
        "jq",
        "jq-lsp",
        "json-lsp",
        "jsonlint",
        "kotlin-debug-adapter",
        "kotlin-language-server",
        "marksman",
        "shellcheck",
        "shfmt",
        "stylua",
        "yaml-language-server",
        "yq",
      },
    },
  },
}
